version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: comparte-tiempo-postgres
    environment:
      POSTGRES_DB: comparte_tiempo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - comparte-tiempo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  comparte-tiempo-network:
    driver: bridge
